// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanHang215.Models;

#nullable disable

namespace WebBanHang215.Migrations
{
    [DbContext(typeof(WebBanHangCong215Context))]
    [Migration("20250505011942_AddColumnsToDonHang")]
    partial class AddColumnsToDonHang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBanHang215.Models.AnhSanPham", b =>
                {
                    b.Property<int>("MaAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAnh"));

                    b.Property<int>("MaSp")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("URL");

                    b.HasKey("MaAnh")
                        .HasName("PK__AnhSanPh__356240DFD406E406");

                    b.HasIndex("MaSp");

                    b.ToTable("AnhSanPham", (string)null);
                });

            modelBuilder.Entity("WebBanHang215.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTietDh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaChiTietDH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietDh"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaDh")
                        .HasColumnType("int");

                    b.Property<int>("MaSp")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietDh")
                        .HasName("PK__ChiTietD__651E6E6AF0163EB8");

                    b.HasIndex("MaDh");

                    b.HasIndex("MaSp");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("WebBanHang215.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("MaChiTietGh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaChiTietGH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietGh"));

                    b.Property<int>("MaGioHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSp")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietGh")
                        .HasName("PK__ChiTietG__651E71CECF02EB26");

                    b.HasIndex("MaGioHang");

                    b.HasIndex("MaSp");

                    b.ToTable("ChiTietGioHang", (string)null);
                });

            modelBuilder.Entity("WebBanHang215.Models.ChiTietSanPham", b =>
                {
                    b.Property<int>("MaCtsp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCtsp"));

                    b.Property<int>("MaMau")
                        .HasColumnType("int");

                    b.Property<int>("MaSize")
                        .HasColumnType("int");

                    b.Property<int>("MaSp")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("MaCtsp")
                        .HasName("PK__ChiTietS__368D46B3F49A3762");

                    b.HasIndex("MaMau");

                    b.HasIndex("MaSize");

                    b.HasIndex("MaSp");

                    b.ToTable("ChiTietSanPham", (string)null);
                });

            modelBuilder.Entity("WebBanHang215.Models.DonHang", b =>
                {
                    b.Property<int>("MaDh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDh"));

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaGiaoDich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaKm")
                        .HasColumnType("int");

                    b.Property<int>("MaNd")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDatHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayGiaoDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayGiaoThucTe")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThaiThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDh")
                        .HasName("PK__DonHang__27258641201D96E5");

                    b.HasIndex("MaKm");

                    b.HasIndex("MaNd");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("WebBanHang215.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"));

                    b.Property<int>("MaNd")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaGioHang")
                        .HasName("PK__GioHang__F5001DA3CE6ED011");

                    b.HasIndex("MaNd");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("WebBanHang215.Models.GioiTinh", b =>
                {
                    b.Property<int>("MaGioiTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioiTinh"));

                    b.Property<string>("TenGioiTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaGioiTinh")
                        .HasName("PK__GioiTinh__46AF33FAA3D4A0C2");

                    b.ToTable("GioiTinh", (string)null);
                });

            modelBuilder.Entity("WebBanHang215.Models.HangSanXuat", b =>
                {
                    b.Property<int>("MaHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHang"));

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHang")
                        .HasName("PK__HangSanX__19C0DB1D9931CE2C");

                    b.ToTable("HangSanXuat", (string)null);
                });

            modelBuilder.Entity("WebBanHang215.Models.KhuyenMai", b =>
                {
                    b.Property<int>("MaKm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKm"));

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<decimal?>("PhanTramGiam")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("TenKhuyenMai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKm")
                        .HasName("PK__KhuyenMa__2725CF75552DF546");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("WebBanHang215.Models.KhuyenMaiSanPham", b =>
                {
                    b.Property<int>("MaKm")
                        .HasColumnType("int");

                    b.Property<int>("MaSp")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.HasKey("MaKm", "MaSp");

                    b.HasIndex("MaSp");

                    b.ToTable("KhuyenMai_SanPham", (string)null);
                });

            modelBuilder.Entity("WebBanHang215.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai")
                        .HasName("PK__LoaiSanP__730A575941BF782D");

                    b.ToTable("LoaiSanPham", (string)null);
                });

            modelBuilder.Entity("WebBanHang215.Models.MauSac", b =>
                {
                    b.Property<int>("MaMau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMau"));

                    b.Property<string>("MaMauHex")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("char(7)")
                        .IsFixedLength();

                    b.Property<string>("TenMau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaMau")
                        .HasName("PK__MauSac__3A5BBB7D4863F143");

                    b.ToTable("MauSac", (string)null);
                });

            modelBuilder.Entity("WebBanHang215.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNd"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoVaTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNd")
                        .HasName("PK__NguoiDun__2725D7048DBFE1DE");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("WebBanHang215.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNcc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNcc"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNhaCungCap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNcc")
                        .HasName("PK__NhaCungC__3A1951E314162D6D");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("WebBanHang215.Models.SanPham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSp"));

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GiaKhuyenMai")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaGioiTinh")
                        .HasColumnType("int");

                    b.Property<int>("MaHang")
                        .HasColumnType("int");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<int>("MaNcc")
                        .HasColumnType("int");

                    b.Property<int>("MaTrangThai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongNhap")
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__2725087C19D07A26");

                    b.HasIndex("MaGioiTinh");

                    b.HasIndex("MaHang");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaNcc");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("WebBanHang215.Models.Size", b =>
                {
                    b.Property<int>("MaSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSize"));

                    b.Property<string>("LoaiSize")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TenSize")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSize")
                        .HasName("PK__Size__A787E7ED6018E466");

                    b.ToTable("Size", (string)null);
                });

            modelBuilder.Entity("WebBanHang215.Models.TrangThaiSanPham", b =>
                {
                    b.Property<int>("MaTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTrangThai"));

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTrangThai")
                        .HasName("PK__TrangTha__AADE41382D6E30CA");

                    b.ToTable("TrangThaiSanPham", (string)null);
                });

            modelBuilder.Entity("WebBanHang215.Models.AnhSanPham", b =>
                {
                    b.HasOne("WebBanHang215.Models.SanPham", "MaSpNavigation")
                        .WithMany("AnhSanPhams")
                        .HasForeignKey("MaSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AnhSanPham_SanPham");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("WebBanHang215.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("WebBanHang215.Models.DonHang", "MaDhNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDh")
                        .IsRequired()
                        .HasConstraintName("FK_CTDonHang_DonHang");

                    b.HasOne("WebBanHang215.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK_CTDonHang_SanPham");

                    b.Navigation("MaDhNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("WebBanHang215.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("WebBanHang215.Models.GioHang", "MaGioHangNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGioHang")
                        .IsRequired()
                        .HasConstraintName("FK_CTGioHang_GioHang");

                    b.HasOne("WebBanHang215.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK_CTGioHang_SanPham");

                    b.Navigation("MaGioHangNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("WebBanHang215.Models.ChiTietSanPham", b =>
                {
                    b.HasOne("WebBanHang215.Models.MauSac", "MaMauNavigation")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MaMau")
                        .IsRequired()
                        .HasConstraintName("FK_CTSP_Mau");

                    b.HasOne("WebBanHang215.Models.Size", "MaSizeNavigation")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MaSize")
                        .IsRequired()
                        .HasConstraintName("FK_CTSP_Size");

                    b.HasOne("WebBanHang215.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK_CTSP_SanPham");

                    b.Navigation("MaMauNavigation");

                    b.Navigation("MaSizeNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("WebBanHang215.Models.DonHang", b =>
                {
                    b.HasOne("WebBanHang215.Models.KhuyenMai", "MaKmNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKm")
                        .HasConstraintName("FK_DonHang_KhuyenMai");

                    b.HasOne("WebBanHang215.Models.NguoiDung", "MaNdNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNd")
                        .IsRequired()
                        .HasConstraintName("FK_DonHang_NguoiDung");

                    b.Navigation("MaKmNavigation");

                    b.Navigation("MaNdNavigation");
                });

            modelBuilder.Entity("WebBanHang215.Models.GioHang", b =>
                {
                    b.HasOne("WebBanHang215.Models.NguoiDung", "MaNdNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaNd")
                        .IsRequired()
                        .HasConstraintName("FK_GioHang_NguoiDung");

                    b.Navigation("MaNdNavigation");
                });

            modelBuilder.Entity("WebBanHang215.Models.KhuyenMaiSanPham", b =>
                {
                    b.HasOne("WebBanHang215.Models.KhuyenMai", "MaKmNavigation")
                        .WithMany("KhuyenMaiSanPhams")
                        .HasForeignKey("MaKm")
                        .IsRequired()
                        .HasConstraintName("FK_KM_SP_KM");

                    b.HasOne("WebBanHang215.Models.SanPham", "MaSpNavigation")
                        .WithMany("KhuyenMaiSanPhams")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK_KM_SP_SP");

                    b.Navigation("MaKmNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("WebBanHang215.Models.SanPham", b =>
                {
                    b.HasOne("WebBanHang215.Models.GioiTinh", "MaGioiTinhNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaGioiTinh")
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_GioiTinh");

                    b.HasOne("WebBanHang215.Models.HangSanXuat", "MaHangNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaHang")
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_HangSanXuat");

                    b.HasOne("WebBanHang215.Models.LoaiSanPham", "MaLoaiNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoai")
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_LoaiSanPham");

                    b.HasOne("WebBanHang215.Models.NhaCungCap", "MaNccNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaNcc")
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_NhaCungCap");

                    b.HasOne("WebBanHang215.Models.TrangThaiSanPham", "MaTrangThaiNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaTrangThai")
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_TrangThai");

                    b.Navigation("MaGioiTinhNavigation");

                    b.Navigation("MaHangNavigation");

                    b.Navigation("MaLoaiNavigation");

                    b.Navigation("MaNccNavigation");

                    b.Navigation("MaTrangThaiNavigation");
                });

            modelBuilder.Entity("WebBanHang215.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("WebBanHang215.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("WebBanHang215.Models.GioiTinh", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebBanHang215.Models.HangSanXuat", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebBanHang215.Models.KhuyenMai", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("KhuyenMaiSanPhams");
                });

            modelBuilder.Entity("WebBanHang215.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebBanHang215.Models.MauSac", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("WebBanHang215.Models.NguoiDung", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("WebBanHang215.Models.NhaCungCap", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebBanHang215.Models.SanPham", b =>
                {
                    b.Navigation("AnhSanPhams");

                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("ChiTietSanPhams");

                    b.Navigation("KhuyenMaiSanPhams");
                });

            modelBuilder.Entity("WebBanHang215.Models.Size", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("WebBanHang215.Models.TrangThaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
